source "https://rubygems.org"

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

gem "sinatra"
gem "net-ssh"
gem "net-scp"
gem "nokogiri"
gem "sqlite3"
gem "unicorn"
gem "bcrypt"
gem "redcarpet"
gem "data_mapper"
gem "dm-sqlite-adapter"
gem "tzinfo"
gem "tzinfo-data"
gem "process_shared"
gem "mail"
gem "htmlentities"
gem "chartkick"
gem "i18n"
gem "activesupport"
gem "unicorn-worker-killer"
gem "erubis"
