source "https://rubygems.org"

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

gem "activesupport", "~>4.2.6"
gem "sinatra", "~>1.4.7"
gem "net-ssh", "~>3.2.0"
gem "net-scp", "~>1.2.1"
gem "nokogiri", "~>1.6.8"
gem "sqlite3", "~>1.3.11"
gem "bcrypt", "~>3.1.11"
gem "redcarpet", "~>3.3.4"
gem "data_mapper", "~>1.2.0"
gem "dm-sqlite-adapter", "~>1.2.0"
gem "tzinfo", "~>1.2.2"
gem "tzinfo-data"
gem "process_shared", "~>0.2.1"
gem "mail", "~>2.6.4"
gem "htmlentities", "~>4.3.4"
gem "chartkick", "~>2.1.1"
gem "i18n", "~>0.7.0"
gem "unicorn", "~>4.9"
gem "unicorn-worker-killer", "~>0.4.4"
gem "erubis", "~>2.7.0"
